# Generated by Django 4.1.4 on 2023-02-04 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField(max_length=8)),
                ('sexo', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=11)),
                ('endereço', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('escolaridade', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(max_length=8)),
                ('curso', models.CharField(max_length=255)),
                ('modulo', models.CharField(max_length=8)),
                ('responsavel', models.CharField(blank=True, max_length=255)),
                ('cpf_responsavel', models.CharField(blank=True, max_length=11)),
                ('tel', models.CharField(blank=True, max_length=11)),
                ('foto', models.ImageField(blank=True, upload_to='pictures/%Y/%m/')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocultar', models.BooleanField(default=False)),
            ],
        ),
    ]
