# Generated by Django 4.1.4 on 2023-02-04 20:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vencimento', models.DateField(max_length=8)),
                ('curso', models.CharField(max_length=255)),
                ('modulo', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=8)),
                ('pagamento', models.DateField(max_length=8)),
                ('valor', models.FloatField()),
                ('desc', models.FloatField()),
                ('acres', models.FloatField()),
                ('total', models.FloatField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocultar', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alunos.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
            },
        ),
    ]
