# Generated by Django 4.1.4 on 2023-02-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensalidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalidade',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='modulo',
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='pagamento',
            field=models.DateField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
